// Fictional demo portfolio. Everything here is made up: domains use the
// reserved .example TLD (RFC 2606), IPs come from TEST-NET ranges (RFC 5737),
// and the GitHub owner is a placeholder. Dates are relative to today so the
// demo never goes stale.

// Local calendar date (not UTC), so "in 9 days" means the same in every time zone.
function day(offset, now) {
  const date = new Date(now)
  date.setDate(date.getDate() + offset)
  const pad = (value) => String(value).padStart(2, '0')
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`
}

function stamp(offset, now) {
  return `${day(offset, now)}T09:00:00.000Z`
}

function lookup({ checkedDaysAgo, a, ns, mx = [], spf = false, registered, registrar, expires }, now) {
  return {
    checkedAt: stamp(-checkedDaysAgo, now),
    dns: {
      a: { value: a ? [a] : [] },
      aaaa: { value: [] },
      cname: { value: [] },
      mx: { value: mx.map((exchange, index) => ({ exchange, priority: (index + 1) * 10 })) },
      ns: { value: ns },
      txt: { value: spf ? [['v=spf1 include:_spf.mail.example ~all']] : [] },
      soa: { value: {} },
    },
    whois: {
      registrar,
      created: `${registered}T12:00:00Z`,
      expires: `${expires}T12:00:00Z`,
      status: ['client transfer prohibited'],
      nameservers: ns,
    },
  }
}

export function getSeedRecords(now = new Date()) {
  const d = (offset) => day(offset, now)
  const added = (offset) => ({ addedAt: stamp(offset, now), editedAt: stamp(offset, now) })
  const ns = ['ns1.dns.example', 'ns2.dns.example']

  const servers = [
    {
      id: 'server_main',
      name: 'Main VPS',
      provider: 'Hetzner',
      packageName: 'CPX21',
      ipAddress: '203.0.113.10',
      cpu: 3,
      ramGb: 4,
      storage: '80 GB NVMe',
      bandwidth: '20 TB',
      os: 'Ubuntu 24.04',
      location: 'Germany',
      hostedServices: ['Shopfront', 'NewsBite', 'Postgres', 'Caddy'],
      connectedProjectIds: ['project_shopfront', 'project_newsbite'],
      cost: 9,
      renewalDate: d(12),
      expiryDate: '',
      status: 'Active',
      notes: 'Production for Shopfront and NewsBite. Nightly backups to object storage.',
      ...added(-400),
    },
    {
      id: 'server_staging',
      name: 'Staging VPS',
      provider: 'DigitalOcean',
      packageName: 'Basic 1 GB',
      ipAddress: '203.0.113.20',
      cpu: 1,
      ramGb: 1,
      storage: '25 GB SSD',
      bandwidth: '1 TB',
      os: 'Debian 12',
      location: 'Netherlands',
      hostedServices: ['Shopfront staging'],
      connectedProjectIds: [],
      cost: 6,
      renewalDate: d(20),
      expiryDate: '',
      status: 'Active',
      notes: 'Nothing important runs here any more. Candidate to cancel.',
      ...added(-300),
    },
  ]

  const domains = [
    {
      id: 'domain_shopfront',
      name: 'shopfront.example',
      provider: 'Porkbun',
      cost: 11,
      renewalDate: d(9),
      expiryDate: d(9),
      status: 'Active',
      notes: 'Main product domain. Auto-renew is OFF, renew by hand.',
      subdomains: [
        { id: 'sub_shop_app', name: 'app', serverId: 'server_main', notes: 'Customer app' },
        { id: 'sub_shop_staging', name: 'staging', serverId: 'server_staging', notes: '' },
      ],
      connectedProjectIds: ['project_shopfront'],
      connectedServerIds: ['server_main'],
      connectedRepoIds: ['repo_shopfront'],
      lookup: lookup({
        checkedDaysAgo: 2,
        a: '203.0.113.10',
        ns,
        mx: ['mx1.mail.example', 'mx2.mail.example'],
        spf: true,
        registered: '2023-03-14',
        registrar: 'Porkbun LLC',
        expires: d(9),
      }, now),
      ...added(-420),
    },
    {
      id: 'domain_newsbite',
      name: 'newsbite.example',
      provider: 'Cloudflare Registrar',
      cost: 10,
      renewalDate: d(190),
      expiryDate: d(190),
      status: 'Active',
      notes: 'Newsletter landing page and sending domain.',
      subdomains: [{ id: 'sub_news_mail', name: 'mail', serverId: '', notes: 'Sending subdomain' }],
      connectedProjectIds: ['project_newsbite'],
      connectedServerIds: ['server_main'],
      connectedRepoIds: ['repo_newsbite'],
      lookup: lookup({
        checkedDaysAgo: 5,
        a: '203.0.113.10',
        ns,
        mx: ['mx1.mail.example'],
        spf: false,
        registered: '2024-06-02',
        registrar: 'Cloudflare, Inc.',
        expires: d(190),
      }, now),
      ...added(-380),
    },
    {
      id: 'domain_cityguide',
      name: 'cityguide.example',
      provider: 'Namecheap',
      cost: 14,
      renewalDate: d(27),
      expiryDate: d(27),
      status: 'Active',
      notes: 'Directory site, hosted on a static host.',
      subdomains: [],
      connectedProjectIds: ['project_cityguide'],
      connectedServerIds: [],
      connectedRepoIds: ['repo_cityguide'],
      ...added(-200),
    },
    {
      id: 'domain_maker',
      name: 'maker.example',
      provider: 'Namecheap',
      cost: 13,
      renewalDate: d(75),
      expiryDate: d(75),
      status: 'Active',
      notes: 'Personal site and blog.',
      subdomains: [],
      connectedProjectIds: [],
      connectedServerIds: [],
      connectedRepoIds: [],
      lookup: lookup({
        checkedDaysAgo: 30,
        a: '203.0.113.30',
        ns,
        registered: '2019-11-20',
        registrar: 'NameCheap, Inc.',
        expires: d(75),
      }, now),
      ...added(-500),
    },
    {
      id: 'domain_shopfront_typo',
      name: 'shop-front.example',
      provider: 'Porkbun',
      cost: 11,
      renewalDate: d(-3),
      expiryDate: d(-3),
      status: 'Expired',
      notes: 'Typo-protection domain. Decide: renew or let go.',
      subdomains: [],
      connectedProjectIds: ['project_shopfront'],
      connectedServerIds: [],
      connectedRepoIds: [],
      ...added(-390),
    },
  ]

  const repo = (id, name, fields) => ({
    id,
    name,
    owner: 'holdings-demo',
    url: `https://github.com/holdings-demo/${fields.slug}`,
    githubUrl: `https://github.com/holdings-demo/${fields.slug}`,
    visibility: 'Private',
    githubHealth: 'Maintained',
    stars: 0,
    forks: 0,
    openIssues: 0,
    watchers: 1,
    connectedDomainIds: [],
    connectedServerIds: [],
    ...fields,
  })

  const repos = [
    repo('repo_shopfront', 'Shopfront', {
      slug: 'shopfront',
      description: 'Storefront builder for small shops.',
      category: 'SaaS',
      projectStatus: 'Production',
      language: 'TypeScript',
      openIssues: 7,
      createdAt: '2023-03-20',
      lastCommitAt: d(-1),
      connectedProjectIds: ['project_shopfront'],
      connectedDomainIds: ['domain_shopfront'],
      connectedServerIds: ['server_main'],
      deployment: 'VPS',
      liveUrl: 'https://app.shopfront.example',
      ...added(-420),
    }),
    repo('repo_newsbite', 'NewsBite', {
      slug: 'newsbite',
      description: 'Weekly newsletter generator.',
      category: 'SaaS',
      projectStatus: 'Production',
      language: 'Python',
      createdAt: '2024-06-05',
      lastCommitAt: d(-20),
      connectedProjectIds: ['project_newsbite'],
      connectedDomainIds: ['domain_newsbite'],
      connectedServerIds: ['server_main'],
      deployment: 'VPS',
      liveUrl: 'https://newsbite.example',
      ...added(-380),
    }),
    repo('repo_cityguide', 'CityGuide', {
      slug: 'cityguide',
      description: 'Static directory of local businesses.',
      category: 'Website',
      projectStatus: 'Maintained',
      language: 'Astro',
      createdAt: '2025-01-11',
      lastCommitAt: d(-240),
      githubHealth: 'Stale',
      connectedProjectIds: ['project_cityguide'],
      connectedDomainIds: ['domain_cityguide'],
      deployment: 'Static host',
      liveUrl: 'https://cityguide.example',
      ...added(-200),
    }),
    repo('repo_inkwell', 'Inkwell CLI', {
      slug: 'inkwell',
      description: 'Open-source Markdown to newsletter CLI.',
      visibility: 'Public',
      category: 'CLI',
      projectStatus: 'Production',
      language: 'Go',
      stars: 214,
      forks: 12,
      openIssues: 4,
      watchers: 6,
      createdAt: '2024-09-01',
      lastCommitAt: d(-9),
      connectedProjectIds: ['project_inkwell'],
      deployment: 'GitHub',
      ...added(-350),
    }),
  ]

  const projects = [
    {
      id: 'project_shopfront',
      name: 'Shopfront',
      slug: 'shopfront',
      description: 'Storefront builder for small shops. The main earner.',
      status: 'Production',
      priority: 'High',
      category: 'SaaS',
      liveUrl: 'https://app.shopfront.example',
      domainIds: ['domain_shopfront', 'domain_shopfront_typo'],
      repoIds: ['repo_shopfront'],
      serverIds: ['server_main'],
      subscriptionIds: ['subscription_postmark', 'subscription_sentry'],
      notes: '',
      ...added(-420),
    },
    {
      id: 'project_newsbite',
      name: 'NewsBite',
      slug: 'newsbite',
      description: 'Weekly newsletter generator with a small paid tier.',
      status: 'Production',
      priority: 'Medium',
      category: 'SaaS',
      liveUrl: 'https://newsbite.example',
      domainIds: ['domain_newsbite'],
      repoIds: ['repo_newsbite'],
      serverIds: ['server_main'],
      subscriptionIds: ['subscription_openai'],
      notes: '',
      ...added(-380),
    },
    {
      id: 'project_cityguide',
      name: 'CityGuide',
      slug: 'cityguide',
      description: 'Static city directory. Earns a little from ads.',
      status: 'Maintained',
      priority: 'Low',
      category: 'Website',
      liveUrl: 'https://cityguide.example',
      domainIds: ['domain_cityguide'],
      repoIds: ['repo_cityguide'],
      serverIds: [],
      subscriptionIds: [],
      notes: 'Thinking about selling this one.',
      ...added(-200),
    },
    {
      id: 'project_inkwell',
      name: 'Inkwell',
      slug: 'inkwell',
      description: 'Open-source CLI that also markets NewsBite.',
      status: 'Production',
      priority: 'Medium',
      category: 'OSS Library',
      liveUrl: '',
      domainIds: [],
      repoIds: ['repo_inkwell'],
      serverIds: [],
      subscriptionIds: [],
      notes: '',
      ...added(-350),
    },
  ]

  const accounts = [
    {
      id: 'account_github',
      name: 'GitHub (holdings-demo)',
      provider: 'GitHub',
      cost: 4,
      renewalDate: d(15),
      expiryDate: '',
      status: 'Active',
      notes: 'Team plan. 2FA on, recovery codes in the password manager.',
      ...added(-500),
    },
    {
      id: 'account_stripe',
      name: 'Stripe',
      provider: 'Stripe',
      cost: 0,
      renewalDate: '',
      expiryDate: '',
      status: 'Active',
      notes: 'Payments for Shopfront and NewsBite.',
      ...added(-420),
    },
  ]

  const subscriptions = [
    {
      id: 'subscription_postmark',
      name: 'Postmark',
      provider: 'Postmark',
      cost: 15,
      renewalDate: d(4),
      expiryDate: '',
      status: 'Active',
      connectedProjectIds: ['project_shopfront'],
      notes: 'Transactional email.',
      ...added(-400),
    },
    {
      id: 'subscription_sentry',
      name: 'Sentry Team',
      provider: 'Sentry',
      cost: 26,
      renewalDate: d(18),
      expiryDate: '',
      status: 'Active',
      connectedProjectIds: ['project_shopfront'],
      notes: 'Price went up from $19 last year.',
      ...added(-330),
    },
    {
      id: 'subscription_openai',
      name: 'OpenAI API',
      provider: 'OpenAI',
      cost: 20,
      renewalDate: d(6),
      expiryDate: '',
      status: 'Active',
      connectedProjectIds: ['project_newsbite'],
      notes: 'Prepaid credits for summaries.',
      ...added(-250),
    },
    {
      id: 'subscription_figma',
      name: 'Figma Professional',
      provider: 'Figma',
      cost: 15,
      renewalDate: d(22),
      expiryDate: '',
      status: 'Active',
      connectedProjectIds: [],
      notes: 'Not linked to any project. Still needed?',
      ...added(-450),
    },
  ]

  return { domains, servers, repos, projects, accounts, subscriptions }
}

export function isRecordsEmpty(records) {
  return Object.values(records).every((items) => !items?.length)
}
